/*
 * Ms Feed API
 * Ms Feed API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.f4.user.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.f4.user.client.model.CommentDTO;
import com.f4.user.client.model.RedisUserDTO;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CommentWithRedisUserDTO
 */
@JsonPropertyOrder({
  CommentWithRedisUserDTO.JSON_PROPERTY_COMMENT_D_T_O,
  CommentWithRedisUserDTO.JSON_PROPERTY_REDIS_USER_D_T_O
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-27T09:24:56.232976487+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.13.0")
public class CommentWithRedisUserDTO {
  public static final String JSON_PROPERTY_COMMENT_D_T_O = "commentDTO";
  @javax.annotation.Nullable
  private CommentDTO commentDTO;

  public static final String JSON_PROPERTY_REDIS_USER_D_T_O = "redisUserDTO";
  @javax.annotation.Nullable
  private RedisUserDTO redisUserDTO;

  public CommentWithRedisUserDTO() {
  }

  public CommentWithRedisUserDTO commentDTO(@javax.annotation.Nullable CommentDTO commentDTO) {
    
    this.commentDTO = commentDTO;
    return this;
  }

  /**
   * Get commentDTO
   * @return commentDTO
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMENT_D_T_O)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CommentDTO getCommentDTO() {
    return commentDTO;
  }


  @JsonProperty(JSON_PROPERTY_COMMENT_D_T_O)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommentDTO(@javax.annotation.Nullable CommentDTO commentDTO) {
    this.commentDTO = commentDTO;
  }


  public CommentWithRedisUserDTO redisUserDTO(@javax.annotation.Nullable RedisUserDTO redisUserDTO) {
    
    this.redisUserDTO = redisUserDTO;
    return this;
  }

  /**
   * Get redisUserDTO
   * @return redisUserDTO
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REDIS_USER_D_T_O)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RedisUserDTO getRedisUserDTO() {
    return redisUserDTO;
  }


  @JsonProperty(JSON_PROPERTY_REDIS_USER_D_T_O)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRedisUserDTO(@javax.annotation.Nullable RedisUserDTO redisUserDTO) {
    this.redisUserDTO = redisUserDTO;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommentWithRedisUserDTO commentWithRedisUserDTO = (CommentWithRedisUserDTO) o;
    return Objects.equals(this.commentDTO, commentWithRedisUserDTO.commentDTO) &&
        Objects.equals(this.redisUserDTO, commentWithRedisUserDTO.redisUserDTO);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commentDTO, redisUserDTO);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommentWithRedisUserDTO {\n");
    sb.append("    commentDTO: ").append(toIndentedString(commentDTO)).append("\n");
    sb.append("    redisUserDTO: ").append(toIndentedString(redisUserDTO)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

