/*
 * Ms Feed API
 * Ms Feed API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.f4.user.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.f4.user.client.model.FeedItemDTO;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * FeedWithOtherDTO
 */
@JsonPropertyOrder({
  FeedWithOtherDTO.JSON_PROPERTY_FEED_ITEM,
  FeedWithOtherDTO.JSON_PROPERTY_USER_NAME,
  FeedWithOtherDTO.JSON_PROPERTY_USER_AVATAR,
  FeedWithOtherDTO.JSON_PROPERTY_LIKE_COUNT,
  FeedWithOtherDTO.JSON_PROPERTY_COMMENT_COUNT,
  FeedWithOtherDTO.JSON_PROPERTY_SHARE_COUNT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-27T08:11:01.300407367+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.13.0")
public class FeedWithOtherDTO {
  public static final String JSON_PROPERTY_FEED_ITEM = "feedItem";
  @javax.annotation.Nullable
  private FeedItemDTO feedItem;

  public static final String JSON_PROPERTY_USER_NAME = "userName";
  @javax.annotation.Nullable
  private String userName;

  public static final String JSON_PROPERTY_USER_AVATAR = "userAvatar";
  @javax.annotation.Nullable
  private String userAvatar;

  public static final String JSON_PROPERTY_LIKE_COUNT = "likeCount";
  @javax.annotation.Nullable
  private Long likeCount;

  public static final String JSON_PROPERTY_COMMENT_COUNT = "commentCount";
  @javax.annotation.Nullable
  private Long commentCount;

  public static final String JSON_PROPERTY_SHARE_COUNT = "shareCount";
  @javax.annotation.Nullable
  private Long shareCount;

  public FeedWithOtherDTO() {
  }

  public FeedWithOtherDTO feedItem(@javax.annotation.Nullable FeedItemDTO feedItem) {
    
    this.feedItem = feedItem;
    return this;
  }

  /**
   * Get feedItem
   * @return feedItem
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FEED_ITEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FeedItemDTO getFeedItem() {
    return feedItem;
  }


  @JsonProperty(JSON_PROPERTY_FEED_ITEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFeedItem(@javax.annotation.Nullable FeedItemDTO feedItem) {
    this.feedItem = feedItem;
  }


  public FeedWithOtherDTO userName(@javax.annotation.Nullable String userName) {
    
    this.userName = userName;
    return this;
  }

  /**
   * Get userName
   * @return userName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserName() {
    return userName;
  }


  @JsonProperty(JSON_PROPERTY_USER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserName(@javax.annotation.Nullable String userName) {
    this.userName = userName;
  }


  public FeedWithOtherDTO userAvatar(@javax.annotation.Nullable String userAvatar) {
    
    this.userAvatar = userAvatar;
    return this;
  }

  /**
   * Get userAvatar
   * @return userAvatar
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_AVATAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserAvatar() {
    return userAvatar;
  }


  @JsonProperty(JSON_PROPERTY_USER_AVATAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserAvatar(@javax.annotation.Nullable String userAvatar) {
    this.userAvatar = userAvatar;
  }


  public FeedWithOtherDTO likeCount(@javax.annotation.Nullable Long likeCount) {
    
    this.likeCount = likeCount;
    return this;
  }

  /**
   * Get likeCount
   * @return likeCount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LIKE_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getLikeCount() {
    return likeCount;
  }


  @JsonProperty(JSON_PROPERTY_LIKE_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLikeCount(@javax.annotation.Nullable Long likeCount) {
    this.likeCount = likeCount;
  }


  public FeedWithOtherDTO commentCount(@javax.annotation.Nullable Long commentCount) {
    
    this.commentCount = commentCount;
    return this;
  }

  /**
   * Get commentCount
   * @return commentCount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMENT_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCommentCount() {
    return commentCount;
  }


  @JsonProperty(JSON_PROPERTY_COMMENT_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommentCount(@javax.annotation.Nullable Long commentCount) {
    this.commentCount = commentCount;
  }


  public FeedWithOtherDTO shareCount(@javax.annotation.Nullable Long shareCount) {
    
    this.shareCount = shareCount;
    return this;
  }

  /**
   * Get shareCount
   * @return shareCount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHARE_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getShareCount() {
    return shareCount;
  }


  @JsonProperty(JSON_PROPERTY_SHARE_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShareCount(@javax.annotation.Nullable Long shareCount) {
    this.shareCount = shareCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeedWithOtherDTO feedWithOtherDTO = (FeedWithOtherDTO) o;
    return Objects.equals(this.feedItem, feedWithOtherDTO.feedItem) &&
        Objects.equals(this.userName, feedWithOtherDTO.userName) &&
        Objects.equals(this.userAvatar, feedWithOtherDTO.userAvatar) &&
        Objects.equals(this.likeCount, feedWithOtherDTO.likeCount) &&
        Objects.equals(this.commentCount, feedWithOtherDTO.commentCount) &&
        Objects.equals(this.shareCount, feedWithOtherDTO.shareCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(feedItem, userName, userAvatar, likeCount, commentCount, shareCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeedWithOtherDTO {\n");
    sb.append("    feedItem: ").append(toIndentedString(feedItem)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    userAvatar: ").append(toIndentedString(userAvatar)).append("\n");
    sb.append("    likeCount: ").append(toIndentedString(likeCount)).append("\n");
    sb.append("    commentCount: ").append(toIndentedString(commentCount)).append("\n");
    sb.append("    shareCount: ").append(toIndentedString(shareCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

