/*
 * Ms Commentlike API
 * Ms Commentlike API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.f4.user.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.f4.user.client.model.LikeDTO;
import com.f4.user.client.model.RedisUserDTO;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * LikeWithRedisUserDTO
 */
@JsonPropertyOrder({
  LikeWithRedisUserDTO.JSON_PROPERTY_REDIS_USER_D_T_O,
  LikeWithRedisUserDTO.JSON_PROPERTY_LIKE_D_T_O
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-28T09:20:35.299334524+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.13.0")
public class LikeWithRedisUserDTO {
  public static final String JSON_PROPERTY_REDIS_USER_D_T_O = "redisUserDTO";
  @javax.annotation.Nullable
  private RedisUserDTO redisUserDTO;

  public static final String JSON_PROPERTY_LIKE_D_T_O = "likeDTO";
  @javax.annotation.Nullable
  private LikeDTO likeDTO;

  public LikeWithRedisUserDTO() {
  }

  public LikeWithRedisUserDTO redisUserDTO(@javax.annotation.Nullable RedisUserDTO redisUserDTO) {
    
    this.redisUserDTO = redisUserDTO;
    return this;
  }

  /**
   * Get redisUserDTO
   * @return redisUserDTO
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REDIS_USER_D_T_O)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RedisUserDTO getRedisUserDTO() {
    return redisUserDTO;
  }


  @JsonProperty(JSON_PROPERTY_REDIS_USER_D_T_O)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRedisUserDTO(@javax.annotation.Nullable RedisUserDTO redisUserDTO) {
    this.redisUserDTO = redisUserDTO;
  }


  public LikeWithRedisUserDTO likeDTO(@javax.annotation.Nullable LikeDTO likeDTO) {
    
    this.likeDTO = likeDTO;
    return this;
  }

  /**
   * Get likeDTO
   * @return likeDTO
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LIKE_D_T_O)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LikeDTO getLikeDTO() {
    return likeDTO;
  }


  @JsonProperty(JSON_PROPERTY_LIKE_D_T_O)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLikeDTO(@javax.annotation.Nullable LikeDTO likeDTO) {
    this.likeDTO = likeDTO;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LikeWithRedisUserDTO likeWithRedisUserDTO = (LikeWithRedisUserDTO) o;
    return Objects.equals(this.redisUserDTO, likeWithRedisUserDTO.redisUserDTO) &&
        Objects.equals(this.likeDTO, likeWithRedisUserDTO.likeDTO);
  }

  @Override
  public int hashCode() {
    return Objects.hash(redisUserDTO, likeDTO);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LikeWithRedisUserDTO {\n");
    sb.append("    redisUserDTO: ").append(toIndentedString(redisUserDTO)).append("\n");
    sb.append("    likeDTO: ").append(toIndentedString(likeDTO)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

